### ISSUE TITLE
Validator2 gives a java.lang.OutOfMemoryError exception

### ISSUE THREAD

**Issue by jihonsvik** [difi/vefa-validator-app#19]
Validator2 (http://vefa.difi.no/validator2/) gives an exception, I guess the problem is the size of the file (5332kb).
Screenshot of the exception with backtrace:
![f824b37e-31e8-11e5-8bc7-92c0ae4dc5c0](https://cloud.githubusercontent.com/assets/10721331/9058861/dcc6b7e8-3aa4-11e5-81ea-fa0ced481b88.JPG)

**Comment by klakegg** [comment]
This is not related to this repository.

**Comment by jihonsvik** [comment]
Which reposityory is this related to then?

**Comment by klakegg** [comment]
[vefa-validaor](https://github.com/difi/vefa-validator)
